# Site settings
title: krist00fer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My thoughts on all and nothing. All postings on this weblog, including:
  code, scripts, labs, demos and other items are provided "AS IS" with no
  warranties, and confer no rights. This weblog does not represent the
  thoughts, intentions, plans or strategies of Microsoft. It is solely my
  opinion. Because a weblog is intended to provide a semi-permanent
  point-in-time snapshot, you should not consider out of date posts to
  reflect current thoughts and opinions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://krist00fer.com" # the base hostname & protocol for your site
twitter_username: krist00fer
github_username:  krist00fer
timezone: Europe/Stockholm

# Build settings
markdown: kramdown
