# Site settings
title: k00.io
email: kristofer.liljeblad@live.com
description: > # this means to ignore newlines until "baseurl:"
  	Kristofer Liljeblad’s, Senior Program Manager at Microsoft, view on just about anything. Opinions are mine and
  	might not represent my employer’s. Content on this blog are provided “as is” with no warranties what so ever.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://krist00fer.com" # the base hostname & protocol for your site
twitter_username: krist00fer
github_username:  krist00fer
timezone: Europe/Stockholm

# Build settings
markdown: kramdown
